name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  PROJECT_DIR: /home/user/docker/test-repo

jobs:
  build:
    runs-on: self-hosted

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Copy files
        run: |
          cp -rf * $PROJECT_DIR
          cd $PROJECT_DIR
          echo "Updating files..."

    
      # Set up Docker Buildx (for multi-platform builds)
      #- name: Set up Docker Buildx
      #  uses: docker/setup-buildx-action@v2

      # Cache Docker layers (optional, to speed up builds)
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      # Build Docker image
      #- name: Build Docker image
      #  run: |
      #    docker build -t my-app:${{ github.sha }} .

      # Log in to DockerHub (optional, if pushing to DockerHub)
      #- name: Log in to DockerHub
      #  uses: docker/login-action@v2
      #  with:
      #    username: ${{ secrets.DOCKER_USERNAME }}
      #    password: ${{ secrets.DOCKER_PASSWORD }}

      # Push Docker image to DockerHub (optional)
      #- name: Push Docker image
      #  run: |
      #    docker push my-app:${{ github.sha }}
      
      - name: Run Docker Compose
        run: |
          sudo docker-compose down &&  sudo docker-compose up -d --build --force-recreate
